name: Docker build and push

on:
  release:
    types: [published]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Docker login
        run:
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --push \
            -t svrooij/smartmeter:latest \
            -t svrooij/smartmeter:$(echo $GITHUB_REF | cut -d'/' -f3) \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg BUILD_VERSION=$(echo $GITHUB_REF | cut -d'/' -f3) \
            --build-arg VSC_REF=$(echo ${GITHUB_SHA} | cut -c1-8) \
            .